logger:
    version: 1

    formatters:
        simpleFormater:
            format: '%(asctime)s, %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'

    handlers:
        console:
            class: logging.StreamHandler
            formatter: simpleFormater
            level: DEBUG
            stream: ext://sys.stdout
        file:
            class : logging.handlers.RotatingFileHandler
            formatter: simpleFormater
            level: DEBUG
            filename: C:\conmon\log.txt
            maxBytes: 10485760
            backupCount: 10

    root:
        level: DEBUG
        handlers: [console, file]

service:
    # lip: target local ip
    # lport: target local port
    # rip: target remote ip
    # rport: target remort port
