logger:
    version: 1

    formatters:
        simpleFormater:
            format: '%(asctime)s\t%(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'

    handlers:
        console:
            class: logging.StreamHandler
            formatter: simpleFormater
            level: DEBUG
            stream: ext://sys.stdout
        file:
            class : logging.handlers.RotatingFileHandler
            formatter: simpleFormater
            level: DEBUG
            filename: C:\conmon\log.txt
            maxBytes: 10485760
            backupCount: 10

    root:
        level: DEBUG
        handlers: [console, file]

service:
    # hostip: target host ip (required)
    # hport: target host port
    # sip: target local ip
    # sport: target local port
